### ISSUE TITLE
fbut: discussion about IO

### ISSUE THREAD

**Issue by hasufell** [quchen/articles#24]
I feel the section about IO is a bit short there. A frequently brought up topic in #haskell and pretty much anywhere else is that people refer to IO in terms of **side effects**. I'm not sure how you see this, since there are different definitions of "side effects", but afaiu the purpose of haskell IO is exactly that: having IO _without_ side effects, because... the fact that we "do" IO is represented by the type and that is the **effect**. It's not hidden, it doesn't happen outside of the type system or without the compiler or developer knowing, so it's simply an effect, not a side effect.

If we don't see it that way, then I don't see any way to call haskell *pure* anymore. Opinions?

**Comment by quchen** [comment]
Whether you consider `IO` to be pure depends on who you ask in which context. There is only one function that can perform IO and that's main (apart from black magic, of course), and main is called by the runtime, so you have ordinary IO values during compilation that have nothing to do with side effects. On the other hand, the purpose of IO is to be performed of course, causing arbitrary side effects, so it has an impure feeling to it. I don't think I can answer the question of whether IO is pure or not well enough to write about it to be honest :-|

**Comment by quchen** [comment]
I'll close this because I don't know what to do with the suggestion right now. I'll keep an eye open for IO-purity-related discussions in the future though.
