### ISSUE TITLE
Questionable claim in MFP2

### ISSUE THREAD

**Issue by treeowl** [quchen/articles#29]
> An Applicative computation is statically determined in its shape, so it either always or never fails. Depending on previous results would introduce the Monad constraint anyway.

While it is true that shape of an applicative computation cannot depend directly on a *result* of a previous computation, it can depend on an *effect* of a previous computation. In many if not all `Alternative` instances, `fall _ = empty` seems reasonable, but of course not everything that can fail supports `<|>`.

**Comment by quchen** [comment]
What I meant to say was given `foo :: Applicative f => f a` the value `foo` is either identical to a `fail` call or not. Given a monadic constraint on the other hand allows it to fail conditionally, such as depending on state.

**Comment by treeowl** [comment]
I don't understand what you mean. The parser `sym 'a'` in, `regex-applicative` is not equivalent to `fail`, but it can fail, if the matcher encounters some other character.

**Comment by quchen** [comment]
`RE` in that package is not a Monad with a `fail` function so it's a bit hard to talk about it. Looking at the source, `sym` resolves to a `Symbol` constructor of the `RE` type, which is not a failure state, but something to build some sort of DSL with that is then interpreted later (which is probably where failure comes in?).

But I see the point, especially when I translate the example into something more familiar (Parsec). Tired as I am I'll postpone it to a bookmark to think about it again tomorrow. I have a hunch I'll learn something about Applicative when I grok the problem. :-)

**Comment by treeowl** [comment]
One of the interpretations of the notoriously overloaded Alternative and
MonadPlus classes is that they represent recoverable failure. empty/mzero
are failure, while <|>/mplus offer recovery. The failure class we seek
offers "explained failure", which may or may not be recoverable. While
applicative parsing libraries (that have good reasons for *not* offering a
Monad interface) have not yet reached the maturity of monadic ones, they
seem to have a lot of potential for greater efficiency when they apply. I
think it's good to support that. I think it's especially important in the
context of applicative do, if that is to support partial  pattern matching.

**Comment by treeowl** [comment]
I think I'm the one who's confused.
