### ISSUE TITLE
Innacuracy due to GHC 7.10 in Monad hierachy.

### ISSUE THREAD

**Issue by AJFarmar** [quchen/articles#31]
Under 'Ugly Warts you have the bullet point:

> - Mathematically, all monads are functors, but Haskell does not enforce this hierarchy. [...]

In GHC 7.10, this was added:

```Haskell
class Applicative m => Monad (m :: * -> *) where
   [...]
```

Thus this is no longer true.

**Comment by quchen** [comment]
GHC enforces it, Haskell still doesn't. But you're right, I should at least mention that in the article. But since it's quite outdated anyway I'm not sure whether I shouldn't completely rewrite instead of refurbishing it.
