### ISSUE TITLE
'Write yourself a Brainfuck in an hour' section 2, exercise 3 confusing wording

### ISSUE THREAD

**Issue by kozross** [quchen/articles#33]
'Implement that tape a `repeat` function for it analogous to `Data.List.repeat`.' doesn't sound like an actual sentence, and it makes it very hard to understand what the exercise wants from you. _My_ understanding is that you want the reader to implement a `Stream` of constant values, but I'm not sure exactly.

**Comment by quchen** [comment]
I completely forgot about this issue, woops. Well, better late than never! I’m sure you’re well ahead of Brainfuck tutorials nowadays, but maybe it helps the next person.
