### ISSUE TITLE
Small slip with $

### ISSUE THREAD

**Issue by mfricke1947** [quchen/articles#59]
[I know very little Haskell, so please make allowances here.]
David you write:
"The important take-away message here, again, is that the following two lines are equivalent: both of them calculate f x, and then make the result available inside the (...) under the name y.

y = f x
(...)

f x $ \y -> (...)"

The issue is with the last line. $ expects a function on the left and a 'value' on the right. So shouldn't this be 

\y -> (...) $ f x 

or flip the arguments:

aFun x = x+x
y = aFun 2
aFun y   -- 8

(£) = flip ($) 

aFun 2 £ (\y -> (aFun y)) -- 8

Hope this helps. All the best, Martin

**Comment by quchen** [comment]
Hey there!

It’s true that ($) expects a function on the left, and a value to plug it into. In the example I’m giving, `f x` is a function – `f :: a -> (b -> c) -> c`, so `f x :: (b -> c) -> c`. So we can write `f x $ \y -> (...)` and it’s well-typed for suitably typed `(...)`.

Here’s the term, with all subterms annotated with their types:

```haskell
   f x $ \y -> (...)
-- ^:: a -> (b -> c) -> c

   f x $ \y -> (...)
--   ^:: a

   f x $ \y -> (...)
-- ^^^:: (b -> c) -> c

   f x $ \y -> (...)
--        ^:: b

   f x $ \y -> (...)
--             ^^^^^:: c

   f x $ \y -> (...)
--       ^^^^^^^^^^^:: b -> c

   f x $ \y -> (...)
-- ^^^^^^^^^^^^^^^^^:: c
```

The same term could have been written using parentheses instead of `($)`, and is maybe a little clearer here?

```haskell
f x (\y -> (...))
```

**Comment by mfricke1947** [comment]
Hi David,

Thanks for explaining this.  I overlooked the possibility of f being a function that returned a function and, of course, this is a common case in that functions with 'two parameters’ do exactly that (i.e. currying).

All the best,
Yours,

Martin


On Jun 20, 2019, at 11:37 PM, David Luposchainsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey there!

It’s true that ($) expects a function on the left, and a value to plug it into. In the example I’m giving, f x is a function – f :: a -> (b -> c) -> c, so f x :: (b -> c) -> c. So we can write f x $ \y -> (...) and it’s well-typed for suitably typed (...).

Here’s the term, with all subterms annotated with their types:

   f x $ \y -> (...)
-- ^:: a -> (b -> c) -> c

   f x $ \y -> (...)
--   ^:: a

   f x $ \y -> (...)
-- ^^^:: (b -> c) -> c

   f x $ \y -> (...)
--        ^:: b

   f x $ \y -> (...)
--             ^^^^^:: c

   f x $ \y -> (...)
--       ^^^^^^^^^^^:: b -> c

   f x $ \y -> (...)
-- ^^^^^^^^^^^^^^^^^:: c

The same term could have been written using parentheses instead of ($), and is maybe a little clearer here?

f x (\y -> (...))

**Comment by quchen** [comment]
You’re welcome!

Can we close this issue then? :-)

**Comment by mfricke1947** [comment]
Absolutely.

On Jun 22, 2019, at 11:41 AM, David Luposchainsky <notifications@github.com<mailto:notifications@github.com>> wrote:


You’re welcome!

Can we close this issue then? :-)
