### ISSUE TITLE
Inferred (rank 1) type of moeb could be more general

### ISSUE THREAD

**Issue by Jashweii** [quchen/articles#64]
With an explicit type signature, moeb can be given a more general type
```Haskell
moeb :: ((forall b . (a -> b) -> b) -> c -> a) -> c -> a
moeb f x = go where go = f ($ go) x
```
e.g. compare ``moeb (\a -> bimap a a)`` with/without the explicit rank 3(?) signature - the rank 3 version allows a fixpoint with different parameters.

**Comment by quchen** [comment]
Cleaning up old open issues/discussions.
