### ISSUE TITLE
(a `op`) is \x -> a `op` x

### ISSUE THREAD

**Issue by ksqsf** [quchen/articles#66]
Code from [here](https://github.com/quchen/articles/blob/master/fbut.md#a-op-is-not-x---a-op-x) seems to give expected results in both GHC 9.0.1 and GHC 8.10.4.

```haskell
ghci> let op = undefined
|
ghci> (`op` ()) `seq` ()
()
ghci>
```

**Comment by quchen** [comment]
Interesting, has the behavior changed? I’m scared to look through tons of changelogs to find the reason…

**Comment by quchen** [comment]
Looks indeed like GHC fixed this reproducibly. Removed the section in a81fbe724237e7defdcc2ea14068bbfedceb5458. Thanks for the report!
