### ISSUE TITLE
State where not-bottom assumption was used

### ISSUE THREAD

**Issue by TysonMN** [quchen/articles#67]
In [your excellent article about how the first functor law implying the second in Haskell](https://github.com/quchen/articles/blob/master/second_functor_law.md), I see where you used applied the first functor law and the free theorem, but I don't see where you assumed that none of the types involved were the bottom type.

Do you think you could improve that proof by making the use of this assumption explicit?

**Comment by TysonMN** [comment]
Do we need to assume no bottom type to obtain the free theorem for `fmap`?

**Comment by quchen** [comment]
Cleaning up old open issues/discussions.

I think you mean (well, meant – 2 years ago :grimacing:) _bottom value_, not _type_.

**Comment by TysonMN** [comment]
Really?  I think I meant _type_.
