### ISSUE TITLE
loeb: how to detect non-termination?

### ISSUE THREAD

**Issue by runeksvendsen** [quchen/articles#69]
In the https://github.com/quchen/articles/blob/master/loeb-moeb.md  article it is written:

> The interesting part is that the order of the functions is not necessarily left-to-right. The list elements can be swapped around, as long as the circularity is still resolved (otherwise the function won't terminate):

Can you give a more accurate definition of what this “circularity” means? Ie. what is the exact property that must be satisfied in order to avoid non-termination?

I’m trying to debug an issue in the `hnix` Haskell package where the function [`loebM`](https://hackage.haskell.org/package/hnix-0.16.0/docs/src/Nix.Utils.html#loebM) causes an infinite loop. I’d like to understand exactly why this happens in order to print out a helpful error instead of looping indefinitely.

**Comment by quchen** [comment]
Cleaning up old open issues/discussions.

FWIW this is about logical circularity, i.e. things requiring themselves to be calculated, as in `let x = x in x`.
