### ISSUE TITLE
zipWith question: drop in splitMiddle 

### ISSUE THREAD

**Issue by TysonMN** [quchen/articles#70]
This is a question about your [`zipWith` article](https://github.com/quchen/articles/blob/master/2018-11-22_zipWith_const.md).

In your implementation of `splitMiddle`, did you use

```haskell
secondHalf = zipOverflow firstHalf xs
```

instead of something like

```haskell
secondHalf = drop (length firstHalf) xs
```

because the former only enumerates once while the second enumerates twice?

**Comment by quchen** [comment]
Right, `drop` and `length` would both traverse the list, while zipOverflow just does it once. Both versions are correct though.
