### ISSUE TITLE
Another approach to fix

### ISSUE THREAD

**Issue by mduerig** [quchen/articles#73]
I wanted to share another approach for looking at `fix`. See https://stackoverflow.com/a/74170472/402428

It is similar to your approach B in that it factors out recursion. However, it puts some additional emphasis on understanding fixed-points as a limits. 

Feel free to reference it from here if you think it is helpful.

**Comment by quchen** [comment]
Interesting perspective! Not sure how to incorporate that into my post without rewriting all of it though. I am mostly hoping that people stumble upon my post when trying to understand fix, and lots of other posts, and then find whichever one gives them the right idea.
